
import java.awt.Dimension;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class DriverUI extends javax.swing.JFrame {

    private MiniNet miniNet;
    private DefaultListModel profileListModel = new DefaultListModel();
    private DefaultListModel connectionListModel = new DefaultListModel();
    private DefaultComboBoxModel selectedProfileModel = new DefaultComboBoxModel();
    private List<Profile> profiles;
    private List<Connection> connections;
    
    /**
     * Creates new form DriverGUI
     * Constructor which initialize the components of UI
     */
    public DriverUI() {
        initComponents();
        jListProfiles.setModel(profileListModel);
        jListConnections.setModel(connectionListModel);
        jcmbxSelected.setModel(selectedProfileModel);
        
        miniNet = new MiniNet();
        
        DataSourceReader obj=new DataSourceReader();
        obj.readMiniNetFromFile(miniNet, "people.txt", "relations.txt");
        
        profiles = miniNet.getAllProfiles();
        connections = miniNet.getAllConnections();
        
        reloadProfiles();
        reloadConnections();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSouth = new javax.swing.JPanel();
        btnShowChildren = new javax.swing.JButton();
        btnShowParents = new javax.swing.JButton();
        btnQueryRelation = new javax.swing.JButton();
        btnAddProfile = new javax.swing.JButton();
        btnDeleteProfile = new javax.swing.JButton();
        btnMakeRelation = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();
        jPanelCenter = new javax.swing.JPanel();
        jPanelProfiles = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProfiles = new javax.swing.JList<>();
        jPanelConnections = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListConnections = new javax.swing.JList<>();
        jPanelSelectProfile = new javax.swing.JPanel();
        jcmbxSelected = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniNet");

        jPanelSouth.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        btnShowChildren.setText("Show Children");
        btnShowChildren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowChildrenActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnShowChildren);

        btnShowParents.setText("Show Parents");
        btnShowParents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowParentsActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnShowParents);

        btnQueryRelation.setText("Query Relation");
        btnQueryRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryRelationActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnQueryRelation);

        btnAddProfile.setText("Add Profile");
        btnAddProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProfileActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnAddProfile);

        btnDeleteProfile.setText("Delete Profile");
        btnDeleteProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProfileActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnDeleteProfile);

        btnMakeRelation.setText("Make Relation");
        btnMakeRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeRelationActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnMakeRelation);

        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnViewProfile);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanelSouth.add(btnExit);

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        jPanelCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelCenter.setLayout(new java.awt.GridLayout(3, 1, 10, 10));

        jPanelProfiles.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Profiles"));
        jPanelProfiles.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jListProfiles);

        jPanelProfiles.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelCenter.add(jPanelProfiles);

        jPanelConnections.setBorder(javax.swing.BorderFactory.createTitledBorder("List of Relations"));
        jPanelConnections.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(jListConnections);

        jPanelConnections.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanelCenter.add(jPanelConnections);

        jPanelSelectProfile.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Profile"));
        jPanelSelectProfile.setLayout(new java.awt.BorderLayout(0, 5));

        jPanelSelectProfile.add(jcmbxSelected, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridBagLayout());
        jPanelSelectProfile.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanelCenter.add(jPanelSelectProfile);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProfileActionPerformed
        // TODO add your handling code here:
        AddProfileUI addProfileUI = new AddProfileUI(this, true, miniNet);
        addProfileUI.setLocationRelativeTo(null);
        addProfileUI.setPreferredSize(new Dimension(500, 400));
        addProfileUI.setVisible(true);        
    }//GEN-LAST:event_btnAddProfileActionPerformed

    private void btnDeleteProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProfileActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jcmbxSelected.getSelectedIndex();
        if(selectedIndex <= 0){
            JOptionPane.showMessageDialog(this, "No profile selected!");
        }
        else{
            Profile p = profiles.get(selectedIndex - 1);
            try{
                miniNet.removeProfile(p);
                reloadProfiles();
                reloadConnections();
                JOptionPane.showMessageDialog(this, "Profile deleted from MiniNet.");
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnDeleteProfileActionPerformed

    private void btnMakeRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeRelationActionPerformed
        // TODO add your handling code here:
        MakeRelationUI makeRelationUI = new MakeRelationUI(this, true, miniNet);
        makeRelationUI.setLocationRelativeTo(null);
        makeRelationUI.setVisible(true);
    }//GEN-LAST:event_btnMakeRelationActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedIndex = jcmbxSelected.getSelectedIndex();
        if(selectedIndex <= 0){
            JOptionPane.showMessageDialog(this, "No profile selected!");
        }
        else{
            Profile p = profiles.get(selectedIndex - 1);
            String info = "Name " + p.getName() + ":\n" + "Age " + p.getAge() +  ":\n";
            try{
                info += "Children: ";
                if(p.getChildren().length > 0){
                    Profile[] children = p.getChildren();
                    for(Profile child : children){
                        info += "- " + child.getName()+"\n";
                    }
                }
                else {
                    info += "None";
                }
            }
            catch(Exception e){
                info += "None" +"\n";
            }
            try {
                info += "Parents: ";
                if(p.getParents().length >0){
                    Profile[] parents = p.getParents();
                    for(Profile parent : parents){
                        info += "- " + parent.getName()+"\n";
                    }                
                }
                else {
                    info += "None";
                }             
            }
            catch(Exception e){
                info += "None" +"\n";
                System.out.println(e);
            }

            JOptionPane.showMessageDialog(this, info);
        }        
    }

    private void btnShowChildrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowChildrenActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jcmbxSelected.getSelectedIndex();
        if(selectedIndex <= 0){
            JOptionPane.showMessageDialog(this, "No profile selected!");
        }
        else{
            Profile p = profiles.get(selectedIndex - 1);
            Profile[] children = p.getChildren();
            String info = "Children of profile named " + p.getName() + ":\n";
            for(Profile child : children){
                info += "- " + child.getName()+"\n";
            }
            JOptionPane.showMessageDialog(this, info);
        }
    }//GEN-LAST:event_btnShowChildrenActionPerformed

    private void btnShowParentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowParentsActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jcmbxSelected.getSelectedIndex();
        if(selectedIndex <= 0){
            JOptionPane.showMessageDialog(this, "No profile selected!");
        }
        else{
            Profile p = profiles.get(selectedIndex - 1);
            Profile[] parents;
            try {
                parents = p.getParents();
                String info = "Parent of profile named " + p.getName() + ":\n";
                for(Profile parent : parents){
                    info += "- " + parent.getName()+"\n";
                }
                JOptionPane.showMessageDialog(this, info);
                
            } catch (NoParentException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnShowParentsActionPerformed

    private void btnQueryRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryRelationActionPerformed
        // TODO add your handling code here:
        QueryRelationUI qRelationUI = new QueryRelationUI(this, true, miniNet);
        qRelationUI.setLocationRelativeTo(null);
        qRelationUI.setVisible(true);
    }//GEN-LAST:event_btnQueryRelationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        DriverUI ui = new DriverUI();
        ui.setPreferredSize(new Dimension(700, 600));
        ui.setLocationRelativeTo(null);
        ui.setDefaultCloseOperation(EXIT_ON_CLOSE);
        ui.setVisible(true);
    }

    public void reloadProfiles(){
        profiles = miniNet.getAllProfiles();
        profileListModel.clear();
        selectedProfileModel.removeAllElements();
        selectedProfileModel.addElement("Select a Profile");
        for(Profile p : profiles){
            profileListModel.addElement(p.toString());
            selectedProfileModel.addElement(p.toString());
        }
    }
    
    public void reloadConnections(){
        connections = miniNet.getAllConnections();
        connectionListModel.clear();
        for(Connection c : connections){
            connectionListModel.addElement(c.toString());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProfile;
    private javax.swing.JButton btnDeleteProfile;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMakeRelation;
    private javax.swing.JButton btnQueryRelation;
    private javax.swing.JButton btnShowChildren;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JButton btnShowParents;
    private javax.swing.JList<String> jListConnections;
    private javax.swing.JList<String> jListProfiles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelConnections;
    private javax.swing.JPanel jPanelProfiles;
    private javax.swing.JPanel jPanelSelectProfile;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcmbxSelected;
    // End of variables declaration//GEN-END:variables
}
